import type { Metadata } from "next";
import "./globals.css";

import { Header } from "@/shared/components/header";

export const metadata: Metadata = {
  title: "Blog App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <Header />
        <main className="py-4 sm:py-6 lg:py-8">{children}</main>
      </body>
    </html>
  );
}
